# Generated by Django 5.2.6 on 2026-08-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('WOMPI', 'Wompi'), ('SIMULADO', 'Simulado (desarrollo)')], default='WOMPI', max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=12)),
                ('referencia', models.CharField(blank=True, help_text='Referencia de la pasarela.', max_length=80)),
                ('wompi_id', models.CharField(blank=True, max_length=80)),
                ('wompi_estado', models.CharField(blank=True, help_text='Estado crudo de Wompi.', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
