# Generated by Django 5.2.6 on 2026-08-13 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'atributo',
                'verbose_name_plural': 'atributos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tarifa', models.DecimalField(decimal_places=2, help_text='Tarifa en porcentaje. Ej: 19.00 para IVA 19%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('es_por_defecto', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'impuesto',
                'verbose_name_plural': 'impuestos',
                'ordering': ['tarifa'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='inventory.categoria')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('usa_variantes', models.BooleanField(default=False, help_text='Marcar si el producto tiene características especiales (talla, color, tela).')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_max', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atributos', models.ManyToManyField(blank=True, related_name='productos', to='inventory.atributo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventory.categoria')),
                ('impuesto', models.ForeignKey(blank=True, help_text='Impuesto aplicable. Dejar vacío si el producto es exento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventory.impuesto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=60)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='inventory.atributo')),
            ],
            options={
                'verbose_name': 'valor de atributo',
                'verbose_name_plural': 'valores de atributo',
                'ordering': ['atributo', 'orden', 'valor'],
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=60)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio propio; si se deja vacío se usa el del producto.', max_digits=12, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo propio; si se deja vacío se usa el del producto.', max_digits=12, null=True)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventory.producto')),
                ('valores', models.ManyToManyField(related_name='variantes', to='inventory.valoratributo')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ['producto', 'sku'],
            },
        ),
    ]
