# Generated by Django 5.2.6 on 2026-08-13 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='stock',
        ),
        migrations.CreateModel(
            name='StockSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sedes', to='inventory.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='users.sede')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sedes', to='inventory.variante')),
            ],
            options={
                'verbose_name': 'stock por sede',
                'verbose_name_plural': 'stocks por sede',
                'ordering': ['producto__nombre'],
                'unique_together': {('sede', 'producto', 'variante')},
            },
        ),
    ]
