# Generated by Django 5.2.6 on 2026-08-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_producto_stock_remove_variante_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estanteria',
            field=models.CharField(blank=True, max_length=40, verbose_name='Estantería'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modulo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Módulo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nivel',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='variante',
            name='estanteria',
            field=models.CharField(blank=True, max_length=40, verbose_name='Estantería'),
        ),
        migrations.AddField(
            model_name='variante',
            name='modulo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Módulo'),
        ),
        migrations.AddField(
            model_name='variante',
            name='nivel',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nivel'),
        ),
    ]
